Traceback (most recent call last):
  File "/Users/michaeladams/.pyenv/versions/3.7.13/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 64, in single_nb_execution
    **kwargs,
  File "/Users/michaeladams/.pyenv/versions/3.7.13/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/michaeladams/.pyenv/versions/3.7.13/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/michaeladams/.pyenv/versions/3.7.13/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/michaeladams/.pyenv/versions/3.7.13/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/michaeladams/.pyenv/versions/3.7.13/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/michaeladams/.pyenv/versions/3.7.13/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/michaeladams/.pyenv/versions/3.7.13/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from typing import List
from tidychef import acquire, preview
from tidychef.selection import XlsSelectable

tables: List[XlsSelectable] = acquire.xls.local("../../tests/fixtures/xls/dates-times.xls", time_format="%m/%d/%Y")

for table in tables:
    print(table.name)
    preview(table)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/3q/wpcx20553xv0hpsjgtq_zl_m0000gp/T/ipykernel_60478/201885690.py[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;32mfrom[0m [0mtidychef[0m[0;34m.[0m[0mselection[0m [0;32mimport[0m [0mXlsSelectable[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[0;32m----> 5[0;31m [0mtables[0m[0;34m:[0m [0mList[0m[0;34m[[0m[0mXlsSelectable[0m[0;34m][0m [0;34m=[0m [0macquire[0m[0;34m.[0m[0mxls[0m[0;34m.[0m[0mlocal[0m[0;34m([0m[0;34m"../../tests/fixtures/xls/dates-times.xls"[0m[0;34m,[0m [0mtime_format[0m[0;34m=[0m[0;34m"%m/%d/%Y"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0;34m[0m[0m
[1;32m      7[0m [0;32mfor[0m [0mtable[0m [0;32min[0m [0mtables[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.pyenv/versions/3.7.13/lib/python3.7/site-packages/tidychef/acquire/xls/local_implemented.py[0m in [0;36mlocal[0;34m(source, selectable, pre_hook, post_hook, tables, **kwargs)[0m
[1;32m     55[0m         [0mpre_hook[0m[0;34m=[0m[0mpre_hook[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     56[0m         [0mpost_hook[0m[0;34m=[0m[0mpost_hook[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 57[0;31m         [0;34m**[0m[0mkwargs[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     58[0m     )
[1;32m     59[0m [0;34m[0m[0m

[0;32m~/.pyenv/versions/3.7.13/lib/python3.7/site-packages/tidychef/acquire/main.py[0m in [0;36macquirer[0;34m(source, reader, selectable, pre_hook, post_hook, **kwargs)[0m
[1;32m     45[0m         [0msource[0m [0;34m=[0m [0mpre_hook[0m[0;34m([0m[0msource[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     46[0m [0;34m[0m[0m
[0;32m---> 47[0;31m     [0mparsed[0m [0;34m=[0m [0mreader[0m[0;34m.[0m[0mparse[0m[0;34m([0m[0msource[0m[0;34m,[0m [0mselectable[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     48[0m [0;34m[0m[0m
[1;32m     49[0m     [0;32mif[0m [0mreader[0m[0;34m.[0m[0mtables[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.pyenv/versions/3.7.13/lib/python3.7/site-packages/tidychef/acquire/xls/local_implemented.py[0m in [0;36mparse[0;34m(self, source, selectable, **kwargs)[0m
[1;32m     87[0m         [0mworkbook[0m[0;34m:[0m [0mxlrd[0m[0;34m.[0m[0mBook[0m [0;34m=[0m [0mxlrd[0m[0;34m.[0m[0mopen_workbook[0m[0;34m([0m[0msource[0m[0;34m,[0m [0mformatting_info[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     88[0m [0;34m[0m[0m
[0;32m---> 89[0;31m         [0msheets[0m [0;34m=[0m [0msheets_from_workbook[0m[0;34m([0m[0msource[0m[0;34m,[0m [0mselectable[0m[0;34m,[0m [0mworkbook[0m[0;34m,[0m [0mcustom_time_formats[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mtables[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     90[0m [0;34m[0m[0m
[1;32m     91[0m         [0;31m# In this instance we've filtered the tables at the point of reading, so[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.pyenv/versions/3.7.13/lib/python3.7/site-packages/tidychef/acquire/xls/shared.py[0m in [0;36msheets_from_workbook[0;34m(source, selectable, workbook, custom_time_formats, tables_regex, **kwargs)[0m
[1;32m     53[0m             [0;32mif[0m [0;32mnot[0m [0mre[0m[0;34m.[0m[0mmatch[0m[0;34m([0m[0mtables_regex[0m[0;34m,[0m [0mworksheet_name[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     54[0m                 [0;32mcontinue[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 55[0;31m         [0mworksheet[0m [0;34m=[0m [0mworkbook[0m[0;34m.[0m[0msheet_by_name[0m[0;34m([0m[0mworksheet_name[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     56[0m [0;34m[0m[0m
[1;32m     57[0m         [0mtable[0m [0;34m=[0m [0mTable[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: sheet_by_name() got an unexpected keyword argument 'time_format'
TypeError: sheet_by_name() got an unexpected keyword argument 'time_format'

